### ISSUE TITLE
Data loading fails in Python 2.7

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcproject-wq-processing#28]
Error
Traceback (most recent call last):
  File "C:\Users\Andy\Documents\arcproject-wq-processing\scripts\tests\test_wqt_unittest.py", line 34, in test_data_insert
    wqt_timestamp_match.wq_df2database(matched, session=self.session)
  File "C:\Users\Andy\Documents\arcproject-wq-processing\scripts\wqt_timestamp_match.py", line 319, in wq_df2database
    make_record(field_map, row, session, site_function)
  File "C:\Users\Andy\Documents\arcproject-wq-processing\scripts\wqt_timestamp_match.py", line 334, in make_record
    wq.site = site_function(record=row, session=session)  # run the function to determine the record's site code
  File "C:\Users\Andy\Documents\arcproject-wq-processing\scripts\wqt_timestamp_match.py", line 281, in site_function_historic
    filename = getattr(record, source_field)  # get the value of the data source field (source_field defined globally)
AttributeError: 'tuple' object has no attribute 'WQ_SOURCE'

**Comment by andybell** [comment]
@nickrsan could this be due to the lack of a field called "WQ_SOURCE" in the version of the database that I've been using?

**Comment by nickrsan** [comment]
Good thought, but I don't think so. For now, I've had the database toss the filename since it gets translated largely to the site name - we could store it too, but I didn't have it do that yet.

I *think* what the message is telling us is that it's getting a tuple instead of a named tuple when the code converts the pandas data frame row on line 318. I'll see if I can run it under Python 2.7 or something to reproduce it. I now have a virtual machine that's running 10.4, so I can test it there if I need to.

**Comment by nickrsan** [comment]
This was resolved in the recent commits that address pandas issues across versions.
