### ISSUE TITLE
symbolize by water quality variable

### ISSUE THREAD

**Issue by andybell** [ucd-cws/arcproject-wq-processing#86]
Running the mapping tools that symbolize by water quality variable has an error in arcmap.  
```
Traceback (most recent call last):
  File "<string>", line 648, in execute
  File "<string>", line 114, in insert_layer
  File "C:\Python27\ArcGIS10.4\lib\site-packages\amaptor\functions.py", line 68, in make_layer_with_file_symbology
    layer.dataSource = feature_class
  File "c:\program files (x86)\arcgis\desktop10.4\arcpy\arcpy\arcobjects\_base.py", line 89, in _set
    return setattr(self._arc_object, attr_name, cval(val))
RuntimeError: LayerObject: Set attribute dataSource does not exist

Failed to execute (GenerateMonth).
```

**Comment by nickrsan** [comment]
I've resolved this issue in new versions of amaptor (something that requires one line of code in Pro required a huge function in ArcMap - I really like Pro :)). Updating amaptor to the latest version will resolve this.

Some new issues in mapping have cropped up though, but they're unrelated, so I'll close this issue and file a new one. Mapping still isn't perfect in ArcMap, but the map generates properly for the most part (a few variables have issues).
